import { Map } from "../types/common.types";
import { RawAsset } from "../types/external/asset.types";

export const AssetCollectionsMap: Map<string[]> = {
  Gif: ["image/gif"],
  Vector: ["image/svg+xml"],
  Icon: ["image/vnd.microsoft.icon"],
  "3D": ["model/gltf+json", "model/gltf-binary"],
  Audio: [
    "audio/mpeg",
    "audio/wav",
    "audio/flac",
    "audio/mp4",
    "audio/x-ms-wma",
    "audio/aac",
    "audio/aiff",
    "audio/aiff",
  ],
  Archive: [
    "application/zip",
    "application/x-rar-compressed",
    "application/x-tar",
    "application/gzip",
    "application/x-gzip",
    "application/java-archive",
    "application/x-7z-compressed",
    "application/x-fgz",
    "application/x-webarchive",
  ],
  Video: [
    "video/avi",
    "video/mpeg",
    "video/mpg",
    "video/mpeg",
    "video/mp4",
    "video/x-matroska",
    "video/webm",
    "video/quicktime",
    "video/ogg",
    "video/dvd",
    "video/x-m4v",
    "video/3gpp",
    "video/divx",
    "video/x-xvid",
    "application/mxf",
    "video/x-ms-wmv",
    "video/mpeg",
    "video/x-flv",
    "video/mp2t",
  ],
  Image: [
    "image/jpeg",
    "image/png",
    "image/bmp",
    "image/heic",
    "image/tiff",
    "image/webp",
    "image/x-panasonic-raw",
    "image/x-sony-arw",
    "image/x-nikon-nef",
    "image/x-canon-cr2",
    "image/x-canon-crw",
    "image/x-fuji-raf",
    "image/x-pentax-pef",
    "image/x-olympus-orf",
    "image/x-minolta-mrw",
    "image/x-adobe-dng",
    "image/x-sony-sr2",
    "image/x-sony-srf",
    "image/x-kodak-kdc",
    "image/x-kodak-k25",
    "image/x-kodak-dcr",
    "image/x-sigma-x3f",
    "image/x-epson-erf",
    "image/vnd.fpx",
  ],
  Document: [
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/msword",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.template",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    "application/pdf",
    "application/vnd.ms-xpsdocument",
    "application/oxps",
    "application/vnd.ms-publisher",
    "text/csv",
    "text/plain",
    "application/rtf",
    "application/json",
    "application/vnd.oasis.opendocument.text",
    "application/vnd.oasis.opendocument.text-template",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.presentation-template",
    "application/vnd.oasis.opendocument.graphics",
    "application/vnd.apple.pages",
    "application/vnd.apple.numbers",
    "application/vnd.apple.keynote",
    "text/vcard",
    "text/calendar",
    "text/calendar",
    "text/calendar",
    "text/calendar",
    "application/epub+zip",
    "application/x-mobipocket-ebook",
    "application/photoshop",
    "application/illustrator",
    "application/x-indesign",
    "application/x-fla",
    "application/postscript",
    "application/xcf",
    "application/coreldraw",
    "image/vnd.dwg",
    "application/gpx+xml",
    "application/vnd.google-earth.kml+xml",
    "application/vnd.google-earth.kmz",
    "application/x-ipynb+json",
  ],
};

export const RawAssetLinkVariants: (keyof RawAsset)[] = [
  "masterdata",
  "jpg_300dpi",
  "jpg_300dpi_600x600",
];

export const RawAssetTranslation: Map = {
  titleIPTC: "titleIptc",
  kanalExport: "channelExport",
  dateigroeße: "size",
  schlagwoerter: "keywords",
  ALTtext: "alt",
  land: "language",
  "masterdata.variants.master.link": "link",
  "jpg_300dpi.variants.master.link": "link",
  "jpg_300dpi_600x600.variants.master.link": "link",
  "gueltigkeit.von": "validFrom",
  "gueltigkeit.bis": "validTo",
  schlagwoerterIPTC: "keywordsIptc",
  "masterdata.variants.master.type": "dataType",
  "jpg_300dpi.variants.master.type": "dataType",
  "jpg_300dpi_600x600.variants.master.type": "dataType",
  assetId: "assetId",
  "veroeffentlichung.von": "publishFrom",
  "veroeffentlichung.bis": "publishTo",
  name: "filename",
  ausgabekanal: "outputChannel",
  "nebenmarke.name": "subBrand",
  hauptma: "mainBrand",
};

export const AssetsGroupSizeLimit = 524288000;

export const AssetGrouLengthLimi = 50;

export const AssetSizeLimitsMap = {
  Image: 26214400,
  Audio: 52428800,
  Video: 4194304000,
  Document: 1048576000,
  Gif: 15728640,
  Vector: 250000,
  Icon: 26214400,
  Archive: 1048576000,
  "3D": 26214400,
};
